# Generated by Django 4.1.1 on 2022-09-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_catagory',
            new_name='product_category',
        ),
    ]
